import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Schumacher Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to Schumacher's Next.js boilerplate</h1>
      </main>
    </div>
  )
}
